PRAGMA foreign_keys = ON;

CREATE TABLE users(
  username VARCHAR(20) NOT NULL,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  filename VARCHAR(64),
  password VARCHAR(256) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(username)
);

CREATE TABLE posts(
  postid INT(255),
  filename VARCHAR(64) NOT NULL,
  owner VARCHAR(20) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (postid),
  FOREIGN KEY (owner) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE following(
  username1 VARCHAR(20) NOT NULL,
  username2 VARCHAR(20) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(username1,username2),
  FOREIGN KEY (username1) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (username2) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE comments(
  commentid INT(255),
  owner VARCHAR(20) NOT NULL,
  postid INT(255) NOT NULL,
  text TEXT(1024) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(commentid),
  FOREIGN KEY (postid) REFERENCES posts(postid) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (owner) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE likes(
  owner VARCHAR(20) NOT NULL,
  postid INT(255) NOT NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(owner,postid),
  FOREIGN KEY (postid) REFERENCES posts(postid) ON UPDATE CASCADE ON DELETE CASCADE, 
  FOREIGN KEY (owner) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);